#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
FILESDIR_PATH="${DOCROOT_PATH}/files/"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${FILESDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	echo "Downloading Backdrop Drush Commands..."
	sudo git clone https://github.com/backdrop-contrib/drush.git ~/.drush/backdrop > /dev/null

	# We disable email sending here so site-install does not return an error
	php -d sendmail_path=/bin/true /usr/local/bin/drush site-install \
		-y \
		--site-name='My Backdrop Site' \
		--db-url='mysql://user:user@db/default' \
		--account-mail="admin@example.com" \
		--account-name="admin" \
		--account-pass="admin" || true

	
	# Currently a way to set password at runtime with drush site-install
	drush upwd admin --password=admin > /dev/null
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
time site_install

#-------------------------- END: Execution --------------------------------
